language: elixir
elixir:
  - 1.2.3

cache:
  directories:
  - test_chunks

before_script:
  - "[ -d test_chunks ] || (wget http://lunarco.de/minecraft/chunks/test_chunks.zip && unzip test_chunks.zip)"

notifications:
  irc:
    on_success: change
    skip_join: true
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[%{repository_name}] %{message} #%{build_number} %{build_url}"
      - "[%{repository_name}] %{commit_message} (%{author} on %{branch} %{commit}) %{compare_url}"
