language: elixir
elixir:
  - 1.2.3

notifications:
  irc:
    on_success: change
    skip_join: false
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[%{repository_name}] %{branch}#%{build_number} %{message} %{build_url}"
      - "[%{repository_name}] @%{author} %{commit} %{commit_message} %{compare_url}"
