language: elixir
elixir:
  - 1.2.3

branches:
  only:
  - master
  - dev

cache:
  directories:
  - test_chunks
  - deps

install:
  - mix local.hex --force
  - mix deps.get

before_script:
  - "[ -f test_chunks/chunk_-10_5_1457918629636.dump ] || (travis_retry wget http://lunarco.de/minecraft/chunks/test_chunks.zip && unzip test_chunks.zip)"

script:
- "mix test"

after_success:
- "mix bench -o ''"

after_script:
- "mix credo -a"

notifications:
  irc:
    on_success: change
    on_failure: always
    skip_join: true
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[\x0313%{repository_name} \x0306%{branch}\x03] \x0314%{message}\x03 #%{build_number} %{build_url}"
      - "[\x0313%{repository_name} \x0306%{branch}\x03] %{commit_message} (%{commit} by \x0314%{author}\x03) %{compare_url}"
