language: elixir
elixir:
  - 1.2.3

branches:
  only:
  - master
  - dev

cache:
  directories:
  - test_chunks
  - deps

sudo: required

install:
  - curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh -s -- --yes
  - mix local.hex --force
  - mix deps.get
  - mix rustler.update_rust

before_script:
  - "[ -f test_chunks/chunk_-10_5_1457918629636.dump ] || (travis_retry wget http://lunarco.de/minecraft/chunks/test_chunks.zip && unzip test_chunks.zip)"

script:
- "mix test"

after_success:
- "mix bench -o ''"

after_script:
- "mix credo"

notifications:
  irc:
    on_success: change
    on_failure: change
    skip_join: true
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[%{repository_name} %{branch}] %{message} #%{build_number} %{build_url}"
      - "[%{repository_name} %{branch}] %{commit_message} (%{commit} by %{author}) %{compare_url}"
