language: elixir
elixir:
  - 1.2.3

cache:
  directories:
  - test_chunks

before_script:
  - "[ -f test_chunks/chunk_-10_5_1457918629636.dump ] || (wget http://lunarco.de/minecraft/chunks/test_chunks.zip && unzip test_chunks.zip)"

script:
- "mix test"

after_script:
- "mix credo"

notifications:
  irc:
    on_success: change
    skip_join: true
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[%{repository_name} %{branch}] %{message} #%{build_number} %{build_url}"
      - "[%{repository_name} %{branch}] %{commit_message} (%{commit} by %{author}) %{compare_url}"
