[package]
name = "mc_chunk_native"
version = "0.1.0"

[lib]
name = "mc_chunk_native"
path = "src/nif.rs"
crate_type = ["dylib"]

[dependencies]
libc = ">=0.1"
byteorder = "0.3.11"
rustler = "=0.8.1"
rustler_codegen = "=0.8.1"
